---
services:
  redis-db:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    user: "1000:1000"
    command: ["--save", "1", "1"]

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-db
    image: wave-data-analysis:1.0
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST_IP=redis-db
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
    command: src/flask_api.py

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-db
    image: wave-data-analysis:1.0
    environment:
      - REDIS_HOST_IP=redis-db
      - LOG_LEVEL=INFO
    command: src/worker.py
...